FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY . .
RUN yarn install --production
EXPOSE 3000
# RUN chown -R node /app
# USER node
CMD ["node", "--inspect=0.0.0.0:9229", "--nolazy", "src/index.js"]